version: '3'

services:
  ecs_flask_app:
    build: .
    container_name:
      ecs_flask_app
#    ports:
#      - "8000:8000"

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    ports:
      - "80:80"


networks:
  default:
    driver:
      bridge
